env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

snapshot:
  name_template: "{{ incpatch .Version }}-next"

builds:
  - main: ./cmd/mollie/main.go
    binary: mollie
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"

universal_binaries:
  - replace: false

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - completions/*
      - manpages/*

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: "New Features and updates"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other work
      order: 999
  filters:
    exclude:
      - ^test
      - changelog
      - typo
      - Readme
      - ^Merge pull request
      - ^Merge branch
