mollie:
  core:
    # Speficy the environment variable that you want to use to
    # insert your API key.
    key: ${MOLLIE_API_TOKEN}
    # Print JSON instead of the standard tab formatted format.
    json: false
    # Enables verbose logging during the command execution.
    verbose: false
    # Enables printing the curl representation for the request
    # performed, useful for importing to other tools like postman,
    # insomnia, etc...
    curl: false
    # For some features it is necessary to specify the type of
    # actions being performed especially when using organization
    # tokens. Accepted values are test/live.
    mode: test
    # Debug prints the report caller on log entries.
    debug: true
    # Set a custom path to parse config, by default the CLI will
    # attempt to parse from ~, ~/.config, and the current working
    # directory (pwd).
    config:
      default: true
      custom_path: "."
  # Fields are each of the data points returned as part of a response
  # all contains all the possible printable values and printable must
  # contain the values you want to print by default, printable can be
  # overwritten by using the persistent `-f` flag.
  fields:
    payments:
      all:
        - "RESOURCE"
        - "ID"
        - "MODE"
        - "STATUS"
        - "CANCELABLE"
        - "AMOUNT"
        - "METHOD"
        - "DESCRIPTION"
        - "SEQUENCE"
        - "REMAINING"
        - "REFUNDED"
        - "CAPTURED"
        - "SETTLEMENT"
        - "APP_FEE"
        - "CREATED_AT"
        - "AUTHORIZED_AT"
        - "EXPIRES"
        - "PAID_AT"
        - "FAILED_AT"
        - "CANCELED_AT"
        - "CUSTOMER_ID"
        - "SETTLEMENT_ID"
        - "MANDATE_ID"
        - "SUBSCRIPTION_ID"
        - "ORDER_ID"
        - "REDIRECT"
        - "WEBHOOK"
        - "LOCALE"
        - "COUNTRY"
      printable:
        - "ID"
        - "MODE"
        - "STATUS"
        - "AMOUNT"
        - "METHOD"
        - "DESCRIPTION"
        - "COUNTRY"
    customers:
      all:
        - "RESOURCE"
        - "ID"
        - "MODE"
        - "NAME"
        - "EMAIL"
        - "LOCALE"
        - "METADATA"
        - "CREATED_AT"
      printable:
        - "ID"
        - "NAME"
        - "EMAIL"
        - "LOCALE"
        - "METADATA"
        - "CREATED_AT"
    methods:
      all:
        - "RESOURCE"
        - "ID"
        - "DESCRIPTION"
        - "ISSUERS"
        - "MIN_AMOUNT"
        - "MAX_AMOUNT"
        - "LOGO"
      printable:
        - "ID"
        - "DESCRIPTION"
        - "ISSUERS"
        - "MIN_AMOUNT"
        - "MAX_AMOUNT"
    permissions:
      all:
      printable:
    profiles:
      all:
      printable:
    captures:
      all:
        - "RESOURCE"
        - "ID"
        - "MODE"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "PAYMENT_ID"
        - "SHIPMENT_ID"
        - "SETTLEMENT_ID"
        - "CREATED_AT"
      printable:
        - "ID"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "CREATED_AT"
    chargebacks:
      all:
        - "RESOURCE"
        - "ID"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "CREATED_AT"
        - "REVERSED_AT"
        - "PAYMENT_ID"
      printable:
        - "ID"
        - "PAYMENT_ID"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "CREATED_AT"
        - "REVERSED_AT"
    refunds:
      all:
      printable:
    invoices:
      all:
        - "RESOURCE"
        - "ID"
        - "REFERENCE"
        - "VAT_NUMBER"
        - "STATUS"
        - "ISSUED_AT"
        - "PAID_AT"
        - "DUE_AT"
        - "NET_AMOUNT"
        - "VAT_AMOUNT"
        - "GROSS_AMOUNT"
      printable:
        - "ID"
        - "REFERENCE"
        - "VAT_NUMBER"
        - "STATUS"
        - "NET_AMOUNT"
        - "VAT_AMOUNT"
        - "GROSS_AMOUNT"
