mollie:
  core:
    json: false
    verbose: false
    curl: false
    mode: test
    debug: true
    config:
      default: true
      custom_path: "."
  fields:
    payments:
      all:
        - "RESOURCE"
        - "ID"
        - "MODE"
        - "STATUS"
        - "CANCELABLE"
        - "AMOUNT"
        - "METHOD"
        - "DESCRIPTION"
        - "SEQUENCE"
        - "REMAINING"
        - "REFUNDED"
        - "CAPTURED"
        - "SETTLEMENT"
        - "APP_FEE"
        - "CREATED_AT"
        - "AUTHORIZED_AT"
        - "EXPIRES"
        - "PAID_AT"
        - "FAILED_AT"
        - "CANCELED_AT"
        - "CUSTOMER_ID"
        - "SETTLEMENT_ID"
        - "MANDATE_ID"
        - "SUBSCRIPTION_ID"
        - "ORDER_ID"
        - "REDIRECT"
        - "WEBHOOK"
        - "LOCALE"
        - "COUNTRY"
      printable:
        - "ID"
        - "MODE"
        - "STATUS"
        - "AMOUNT"
        - "METHOD"
        - "DESCRIPTION"
        - "COUNTRY"
    customers:
      all:
        - "RESOURCE"
        - "ID"
        - "MODE"
        - "NAME"
        - "EMAIL"
        - "LOCALE"
        - "METADATA"
        - "CREATED_AT"
      printable:
        - "ID"
        - "NAME"
        - "EMAIL"
        - "LOCALE"
        - "METADATA"
        - "CREATED_AT"
    methods:
      all:
        - "RESOURCE"
        - "ID"
        - "DESCRIPTION"
        - "ISSUERS"
        - "MIN_AMOUNT"
        - "MAX_AMOUNT"
        - "LOGO"
      printable:
        - "ID"
        - "DESCRIPTION"
        - "ISSUERS"
        - "MIN_AMOUNT"
        - "MAX_AMOUNT"
    permissions:
      all:
        - "RESOURCE"
        - "ID"
        - "DESCRIPTION"
        - "GRANTED"
      printable:
        - "ID"
        - "DESCRIPTION"
        - "GRANTED"
    profiles:
      all:
        - "RESOURCE"
        - "ID"
        - "MODE"
        - "NAME"
        - "WEBSITE"
        - "EMAIL"
        - "PHONE"
        - "CATEGORY_CODE"
        - "STATUS"
        - "REVIEW"
        - "CREATED_AT"
      printable:
        - "ID"
        - "NAME"
        - "WEBSITE"
        - "EMAIL"
        - "PHONE"
        - "CATEGORY_CODE"
        - "STATUS"
        - "REVIEW"
    captures:
      all:
        - "RESOURCE"
        - "ID"
        - "MODE"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "PAYMENT_ID"
        - "SHIPMENT_ID"
        - "SETTLEMENT_ID"
        - "CREATED_AT"
      printable:
        - "ID"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "CREATED_AT"
    chargebacks:
      all:
        - "RESOURCE"
        - "ID"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "CREATED_AT"
        - "REVERSED_AT"
        - "PAYMENT_ID"
      printable:
        - "ID"
        - "PAYMENT_ID"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "CREATED_AT"
        - "REVERSED_AT"
    refunds:
      all:
        - "RESOURCE"
        - "ID"
        - "AMOUNT"
        - "SETTLEMENT_ID"
        - "SETTLEMENT_AMOUNT"
        - "DESCRIPTION"
        - "METADATA"
        - "STATUS"
        - "PAYMENT_ID"
        - "ORDER_ID"
        - "CREATED_AT"
      printable:
        - "ID"
        - "AMOUNT"
        - "SETTLEMENT_AMOUNT"
        - "DESCRIPTION"
        - "STATUS"
    invoices:
      all:
        - "RESOURCE"
        - "ID"
        - "REFERENCE"
        - "VAT_NUMBER"
        - "STATUS"
        - "ISSUED_AT"
        - "PAID_AT"
        - "DUE_AT"
        - "NET_AMOUNT"
        - "VAT_AMOUNT"
        - "GROSS_AMOUNT"
      printable:
        - "ID"
        - "REFERENCE"
        - "VAT_NUMBER"
        - "STATUS"
        - "NET_AMOUNT"
        - "VAT_AMOUNT"
        - "GROSS_AMOUNT"
