name: Linting with golangci-lint
on:
  push:
    branches:
      - master
    paths:
      - "commands/**.go"
      - "internal/**/*.go"
      - "pkg/**/*.go"
      - "cmd/*/*.go"
      - "go.*"
  pull_request:
    paths:
      - "commands/**.go"
      - "internal/**/*.go"
      - "pkg/**/*.go"
      - "cmd/*/*.go"
      - "go.*"
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
    name: Golang linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          only-new-issues: true
          args: --issues-exit-code=1 --sort-results --skip-dirs-use-default --tests=false
