name: Golang testing
on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/**.md"
      - ".github/**/**.md"
      - ".github/**.yml"
      - ".github/**/**.yml"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/**.md"
      - ".github/**/**.md"
      - ".github/**.yml"
      - ".github/**/**.yml"
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.17.x, 1.18.x]
    name: Go ${{ matrix.go }} check
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go test -failfast ./...
